# Time series regression model parameters

# LightGBM regressor parameters
lgbm_params:
  n_estimators: 100
  learning_rate: 0.1
  num_leaves: 31
  subsample: 1.0
  colsample_bytree: 1.0
  random_state: 42

# Random Forest regressor parameters
rf_params:
  n_estimators: 100
  criterion: "squared_error"
  max_depth: 3
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: 1.0
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  bootstrap: True
  oob_score: False
  n_jobs: -1
  random_state: 42
  verbose: 0
  warm_start: False
  ccp_alpha: 0.0
  max_samples: null

# XGBoost regressor parameters
xgb_params:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 3
  min_child_weight: 1
  gamma: 0
  subsample: 1
  colsample_bytree: 1
  colsample_bylevel: 1
  colsample_bynode: 1
  reg_alpha: 0
  reg_lambda: 1
  scale_pos_weight: 1
  base_score: 0.5
  random_state: 42
  n_jobs: -1
  verbosity: 1

# CatBoost regressor parameters
cat_params:
  iterations: 100
  learning_rate: 0.03
  depth: 6
  l2_leaf_reg: 3
  bootstrap_type: "Bayesian"
  # subsample: 0.8
  sampling_frequency: "PerTree"
  sampling_unit: "Object"
  colsample_bylevel: 0.8
  random_strength: 1
  bagging_temperature: 0.2
  metric_period: 50
  od_type: "Iter"
  od_wait: 45
  allow_writing_files: False
  random_seed: 42
  verbose: False

# SVR parameters
svm_params:
  kernel: "rbf"
  degree: 3
  gamma: "scale"
  coef0: 0.0
  tol: 0.001
  C: 1.0
  epsilon: 0.1
  shrinking: True
  cache_size: 200
  verbose: False
  max_iter: -1
  # random_state: 42

# KNN regressor parameters
knn_params:
  n_neighbors: 5
  weights: "uniform"
  algorithm: "auto"
  leaf_size: 30
  p: 2
  metric: "minkowski"
  metric_params: null
  n_jobs: -1

# Decision Tree regressor parameters
dt_params:
  criterion: "squared_error"
  splitter: "best"
  max_depth: null
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_features: null
  random_state: 42
  max_leaf_nodes: null
  min_impurity_decrease: 0.0
  ccp_alpha: 0.0

# AdaBoost regressor parameters
ada_params:
  n_estimators: 100
  learning_rate: 1.0
  loss: "linear"
  random_state: 42

# Gradient Boosting time-series forecast regressor parameters
gb_params:
  loss: "squared_error"
  learning_rate: 0.1
  n_estimators: 100
  subsample: 1.0
  criterion: "friedman_mse"
  min_samples_split: 2
  min_samples_leaf: 1
  min_weight_fraction_leaf: 0.0
  max_depth: 3
  min_impurity_decrease: 0.0
  init: null
  random_state: 42
  max_features: null
  alpha: 0.9
  verbose: 0
  max_leaf_nodes: null
  warm_start: False
  validation_fraction: 0.1
  n_iter_no_change: null
  tol: 0.0001
  ccp_alpha: 0.0
